update

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,15 +1,23 @@
-#!/usr/bin/env bash
-# to 
-if [ $# -lt 4 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-    exit 1
+#!/bin/bash
+# Check if all 4 parameters are provided
+if [ $# -lt 3 ]; then
+  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+export "SSH_OPTIONS=-o StrictHostKeyChecking=no"
+
+scp -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
 
 if [ $? -eq 0 ]; then
-    echo "File transfer successful!"
+  echo "File transferred successfully."
 else
-    echo "File transfer failed!"
+  echo "Error transferring the file."
 fi
 
